// Hand corpus for golem's register: bare noun phrases, closed questions, and the few imperatives golem has.
// `node golem-corpus.mjs [pt]` prints the verdicts; golden/golem-en.txt and golden/golem-pt.txt are the gates.
import { ENGLISH, PORTUGUESE } from '../src/main.js';
import { runCorpus } from './corpus.mjs';
import { readFileSync } from 'node:fs';

export const GOLEM = JSON.parse(readFileSync(new URL('./golem.json', import.meta.url), 'utf8'));

export const GOLEM_EN = [
  ['— conversions: a bare quantity and a unit —'],
  '0.35 oz per short ton in g/t',
  '2.7 g/cm3 in lb/ft3',
  '5 km in kg',
  '25 c in f',
  '1500 psi in mpa',
  'convert 2 km to miles',
  'what is 2 km in miles',
  '2 km',
  ['— lookups: a property of a thing —'],
  'density of chalcopyrite',
  'what is the density of chalcopyrite',
  "what's the capital of brazil",
  'population density of mongolia in people per square mile',
  'hardness of pyrite',
  'area of brazil in square miles',
  'density of mongolia',
  'density',
  ['— plots —'],
  'histogram of cu',
  'plot a histogram of gold',
  'histogram of cu in log scale',
  'variogram of cu',
  'histogram of grade',
  'histogram of chalcopyrite',
  ['— definitions —'],
  'what is a skiplist',
  'define treap',
  'chalcopyrite',
  'explain the hash table',
  ['— lists —'],
  'landlocked countries by population',
  'which countries are landlocked',
  'list landlocked countries by area',
  'countries by population',
  ['— device and session —'],
  'set a timer for 5 min',
  'timer for 10 minutes',
  'export as script',
  'open assays.csv',
  'identify a mineral',
  ['— out of scope and breakers —'],
  'why is the density so high',
  'write me a poem about kriging',
  'cu',
  'log scale',
  'in feet',
  'what is',
  '14 * cos(22) + 3^2',
  'histogram of cu and density of pyrite',
];

export const GOLEM_PT = [
  ['— conversões —'],
  '0.35 oz por tonelada curta em g/t',
  '2.7 g/cm3 em lb/ft3',
  '25 c em f',
  'converte 2 km para milhas',
  'quanto é 2 km em milhas',
  '2 km',
  ['— consultas —'],
  'densidade da calcopirita',
  'qual é a densidade da calcopirita',
  'qual é a capital do brasil',
  'densidade populacional da mongólia em pessoas por milha quadrada',
  'dureza da pirita',
  'área do brasil em milhas quadradas',
  ['— gráficos —'],
  'histograma de cu',
  'plota um histograma de ouro',
  'histograma de cu em escala log',
  'variograma do cobre',
  'histograma do teor',
  ['— definições —'],
  'o que é um skiplist',
  'define treap',
  'calcopirita',
  'explica a tabela hash',
  ['— listas —'],
  'países sem litoral por população',
  'quais países são sem litoral',
  'lista os países sem litoral por área',
  ['— dispositivo e sessão —'],
  'cronômetro de 5 min',
  'timer de 10 minutos',
  'exporta como script',
  'abre assays.csv',
  'identifica um mineral',
  ['— fora de escopo e quebradores —'],
  'por que a densidade está tão alta',
  'escreve um poema sobre krigagem',
  'cu',
  'escala log',
  'em pés',
];

if (/golem-corpus\.mjs$/.test(process.argv[1] ?? '')) {
  const pt = process.argv[2] === 'pt';
  process.stdout.write(runCorpus(pt ? GOLEM_PT : GOLEM_EN, pt ? PORTUGUESE : ENGLISH, { ontology: GOLEM, objects: [] }));
}
